# Generated by Django 4.1.7 on 2025-12-21 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_name", models.CharField(max_length=30)),
                ("first_name", models.CharField(max_length=30)),
                ("age", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="clinicalData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "compponentName",
                    models.CharField(
                        choices=[
                            ("hw", "Height/Weight"),
                            ("bp", "Blood Pressure"),
                            ("heartrate", "Heart Rate"),
                        ],
                        max_length=100,
                    ),
                ),
                ("measuredValue", models.CharField(max_length=50)),
                ("measureDateTime", models.DateTimeField(auto_now_add=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="clinicalsApp.patient",
                    ),
                ),
            ],
        ),
    ]
